kind: ServiceAccount
apiVersion: v1
metadata:
  name: '#{service_name}-sa'
  namespace: '#{namespace}'
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secrets-cgld
  namespace: '#{namespace}'
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get", "list", "delete"]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: serviceaccounts-p
  namespace: '#{namespace}'
rules:
  - apiGroups: [""]
    resources: ["serviceaccounts", "serviceaccounts/token"]
    verbs: ["get", "patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: '#{service_name}-sa--secrets-cgld'
  namespace: '#{namespace}'
subjects:
  - kind: ServiceAccount
    name: '#{service_name}-sa'
    namespace: '#{namespace}'
roleRef:
  kind: Role
  name: secrets-cgld
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: '#{service_name}-sa--serviceaccounts-p'
  namespace: '#{namespace}'
subjects:
  - kind: ServiceAccount
    name: '#{service_name}-sa'
    namespace: '#{namespace}'
roleRef:
  kind: Role
  name: serviceaccounts-p
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding 
apiVersion: rbac.authorization.k8s.io/v1  
metadata:  
  name: '#{service_name}-sa--auth-delegator'
  namespace: '#{namespace}'
subjects:  
- kind: ServiceAccount
  name: '#{service_name}-sa'
  namespace: '#{namespace}'
roleRef:  
  kind: ClusterRole  
  name: system:auth-delegator
  apiGroup: rbac.authorization.k8s.io



