FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base

WORKDIR /app

# Installing curl for testing
RUN apt-get update && apt-get install -y curl

COPY . .

EXPOSE 8080

ENTRYPOINT ["dotnet", "Edrs.ActionListenerService.Webapi.dll"]
