<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
	<PackageReference Include="EasyNetQ" Version="7.8.0" />
	<PackageReference Include="Microsoft.ApplicationInsights" Version="2.23.0" />
    <PackageReference Include="Microsoft.Azure.Storage.Blob" Version="11.2.3" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.2" />
    <PackageReference Include="Microsoft.Azure.WebJobs" Version="3.0.41" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Npgsql" Version="8.0.5" />
    <PackageReference Include="System.Formats.Asn1" Version="8.0.1" />
    <PackageReference Include="System.Security.Cryptography.Pkcs" Version="6.0.3" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="6.0.1" />
    <PackageReference Include="System.ServiceModel.Http" Version="8.0.0" />
    <PackageReference Include="WindowsAzure.Storage" Version="9.3.3" />
	<PackageReference Include="Core.Services.Libraries.Base" Version="1.0.23" />
	<PackageReference Include="Core.Services.Libraries.Http" Version="1.0.23" />
	</ItemGroup>
 
  <ItemGroup>
    <Reference Include="System.Text.Json">
      <HintPath>C:\Users\Murugesan.B\.nuget\packages\system.text.json\9.0.0\lib\net8.0\System.Text.Json.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
